version: "3.6"

x-restart-policy: &restart_policy
  restart: unless-stopped

services:
  postgres:
    <<: *restart_policy
    image: postgres:14
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "3254:5432"

volumes:
  db_data:
